const prisma = require('../config/prisma');
const asyncHandler = require('../middleware/asyncHandler');

// Helper to safely parse JSON if string
const safeJsonParse = (val) => {
  if (val === null || val === undefined || val === '') return null;
  if (typeof val === 'object') return val;
  try {
    return JSON.parse(val);
  } catch (e) {
    return null;
  }
};

// Helper to get all existing active barcode strings from DB
const getAllActiveBarcodesInDB = async (excludeProductId = null) => {
  const activeBarcodes = new Set();

  const productWhere = { isActive: true };
  if (excludeProductId) {
    productWhere.id = { not: parseInt(excludeProductId) };
  }

  const existingProducts = await prisma.product.findMany({
    where: productWhere,
    select: { id: true, barcode: true, brandPrices: true }
  });

  for (const prod of existingProducts) {
    if (prod.barcode && typeof prod.barcode === 'string' && prod.barcode.trim()) {
      activeBarcodes.add(prod.barcode.trim().toLowerCase());
    }

    const parsedBp = safeJsonParse(prod.brandPrices);
    if (parsedBp && typeof parsedBp === 'object') {
      for (const bIdStr of Object.keys(parsedBp)) {
        const bEntry = parsedBp[bIdStr];
        if (bEntry && !bEntry.isDeleted && bEntry.barcode && typeof bEntry.barcode === 'string' && bEntry.barcode.trim()) {
          activeBarcodes.add(bEntry.barcode.trim().toLowerCase());
        }
      }
    }
  }

  const existingBrands = await prisma.brand.findMany({
    where: { isActive: true, barcode: { not: null } },
    select: { id: true, barcode: true }
  });

  for (const b of existingBrands) {
    if (b.barcode && typeof b.barcode === 'string' && b.barcode.trim()) {
      activeBarcodes.add(b.barcode.trim().toLowerCase());
    }
  }

  return activeBarcodes;
};

// Helper to generate a candidate barcode string that is guaranteed unique in DB & excludeBarcodes
const generateUniqueBarcodeCandidate = async (excludeBarcodes = [], excludeProductId = null) => {
  const existingSet = await getAllActiveBarcodesInDB(excludeProductId);
  const excludeSet = new Set((excludeBarcodes || []).map(b => (b || '').toString().trim().toLowerCase()));

  let candidate = '';
  let attempts = 0;

  while (attempts < 500) {
    attempts++;
    const ts = Date.now().toString().slice(-8);
    const rand = Math.floor(1000 + Math.random() * 9000).toString();
    candidate = `BC${ts}${rand}`;

    const lowerCandidate = candidate.toLowerCase();
    if (!existingSet.has(lowerCandidate) && !excludeSet.has(lowerCandidate)) {
      return candidate;
    }
  }

  return `BC${Date.now()}${Math.floor(Math.random() * 100000)}`;
};

// Controller endpoint to return a guaranteed unique barcode
exports.getUniqueBarcode = asyncHandler(async (req, res) => {
  const excludeQuery = req.query.exclude || '';
  const excludeList = excludeQuery.split(',').map(s => s.trim()).filter(Boolean);
  const excludeProductId = req.query.excludeProductId ? parseInt(req.query.excludeProductId) : null;

  const uniqueBarcode = await generateUniqueBarcodeCandidate(excludeList, excludeProductId);
  res.json({ barcode: uniqueBarcode });
});

// Helper to process & validate barcodes in create/update payloads
const processAndValidateBarcodes = async (payloadData, excludeProductId = null) => {
  const existingSet = await getAllActiveBarcodesInDB(excludeProductId);
  const payloadSeen = new Set();

  // 1. Process Main Barcode
  let mainBarcode = payloadData.barcode ? payloadData.barcode.trim() : '';
  const mainIsAuto = payloadData.barcodeIsAutoGenerated === true || payloadData.barcodeIsAutoGenerated === 'true';

  if (mainBarcode) {
    const lower = mainBarcode.toLowerCase();
    if (existingSet.has(lower) || payloadSeen.has(lower)) {
      if (mainIsAuto) {
        mainBarcode = await generateUniqueBarcodeCandidate([...existingSet, ...payloadSeen], excludeProductId);
        payloadData.barcode = mainBarcode;
        payloadSeen.add(mainBarcode.toLowerCase());
      } else {
        const err = new Error('Barcode already exists. Please enter a unique barcode.');
        err.statusCode = 400;
        throw err;
      }
    } else {
      payloadSeen.add(lower);
    }
  }

  // 2. Process Brand Prices Barcodes
  let parsedBp = payloadData.brandPrices;
  if (typeof parsedBp === 'string') {
    parsedBp = safeJsonParse(parsedBp);
  }

  if (parsedBp && typeof parsedBp === 'object') {
    for (const bIdStr of Object.keys(parsedBp)) {
      const bEntry = parsedBp[bIdStr];
      if (bEntry && !bEntry.isDeleted && bEntry.barcode && typeof bEntry.barcode === 'string' && bEntry.barcode.trim()) {
        let bCode = bEntry.barcode.trim();
        const bLower = bCode.toLowerCase();
        const bIsAuto = bEntry.isAutoGenerated === true || bEntry.isAutoGenerated === 'true';

        if (existingSet.has(bLower) || payloadSeen.has(bLower)) {
          if (bIsAuto) {
            bCode = await generateUniqueBarcodeCandidate([...existingSet, ...payloadSeen], excludeProductId);
            parsedBp[bIdStr].barcode = bCode;
            payloadSeen.add(bCode.toLowerCase());
          } else {
            const err = new Error('Barcode already exists. Please enter a unique barcode.');
            err.statusCode = 400;
            throw err;
          }
        } else {
          payloadSeen.add(bLower);
        }
      }
    }
    payloadData.brandPrices = parsedBp;
  }
};

const checkBarcodeUniqueness = async (barcodesToCheck, excludeProductId = null) => {
  const validBarcodes = (barcodesToCheck || [])
    .filter(b => b && typeof b === 'string' && b.trim().length > 0)
    .map(b => b.trim());

  if (validBarcodes.length === 0) return;
  const dummyPayload = { barcode: validBarcodes[0] };
  await processAndValidateBarcodes(dummyPayload, excludeProductId);
};

// Get All Products
exports.getAllProducts = asyncHandler(async (req, res) => {
  const { branchId: queryBranchId } = req.query;
  const user = req.user;

  // --- BRANCH ENFORCEMENT ---
  let branchId = queryBranchId;
  const isGlobalAdmin = user?.role === 'admin' && !user?.branchId;

  if (!isGlobalAdmin) {
    // Non-global admins (Branch Admin/Staff) are locked to their own branch stock
    branchId = user.branchId;
  }

  const parsedBranchId = branchId && !isNaN(parseInt(branchId)) ? parseInt(branchId) : undefined;

  const whereClause = {};

  // Visibility Rule: Only admins can see inactive products
  if (user?.role !== 'admin') {
    whereClause.isActive = true;
  }

  const products = await prisma.product.findMany({
    where: whereClause,
    include: {
      category: {
        include: {
          defaultLabelDesign: true
        }
      },
      productType: true,
      brand: true,
      stocks: parsedBranchId ? {
        where: { branchId: parsedBranchId }
      } : true
    },
    orderBy: { createdAt: 'desc' }
  });

  // Map stock to a flat structure for frontend compatibility
  const formattedProducts = products.map(p => ({
    ...p,
    // If parsedBranchId is present, we only show stock for THAT branch.
    // If no stock entry exists for that branch, we default to 0.
    stock: parsedBranchId ? (p.stocks[0]?.quantity || 0) : p.stocks.reduce((acc, s) => acc + s.quantity, 0)
  }));

  res.json(formattedProducts);
});

// Create Product
exports.createProduct = asyncHandler(async (req, res) => {
  let {
    name,
    brandId,
    brandName,
    price,
    taxRate,
    taxType,
    taxPercent,
    hsnCode,
    warranty,
    description,
    barcode,
    hasBarcode,
    categoryName,
    categoryId,
    productTypeId,
    productTypeName,
    gender,
    attributes,
    size,
    sizeStocks,
    stock,
    initialStock,
    minDiscount,
    maxDiscount,
    isTaxInclusive
  } = req.body;

  // Handle Image Upload
  let imageUrl = null;
  if (req.file) {
    imageUrl = '/uploads/' + req.file.filename;
  }

  // If brand is selected, resolve Brand's name
  if (brandId && !isNaN(parseInt(brandId))) {
    const assignedBrand = await prisma.brand.findUnique({ where: { id: parseInt(brandId) } });
    if (assignedBrand) {
      brandName = assignedBrand.name;
    }
  }

  // Auto-generate barcode if missing and enabled
  if ((hasBarcode === 'true' || hasBarcode === true) && !barcode) {
    barcode = 'BC' + Date.now().toString().slice(-10) + Math.floor(Math.random() * 1000).toString();
  }

  const priceDecimal = parseFloat(price);
  const taxVal = taxPercent !== undefined ? taxPercent : (taxRate !== undefined ? taxRate : 0);
  const taxRateDecimal = parseFloat(taxVal) || 0;

  // Parse complex JSON fields
  const parsedAttributes = safeJsonParse(attributes);
  const parsedSizeStocks = safeJsonParse(sizeStocks);
  const parsedBrandPrices = safeJsonParse(req.body.brandPrices);

  // Determine stock quantity
  let totalStockQty = 0;
  if (parsedSizeStocks && Array.isArray(parsedSizeStocks) && parsedSizeStocks.length > 0) {
    totalStockQty = parsedSizeStocks.reduce((sum, item) => sum + (parseInt(item.stock, 10) || 0), 0);
  } else if (stock !== undefined && stock !== '') {
    totalStockQty = parseInt(stock, 10) || 0;
  } else if (initialStock !== undefined && initialStock !== '') {
    totalStockQty = parseInt(initialStock, 10) || 0;
  }

  // Validate Barcode Uniqueness globally & auto-repair auto-generated barcodes
  const payloadForValidation = {
    barcode,
    barcodeIsAutoGenerated: req.body.barcodeIsAutoGenerated,
    brandPrices: parsedBrandPrices
  };
  await processAndValidateBarcodes(payloadForValidation, null);
  const finalBarcode = payloadForValidation.barcode || barcode;
  const finalBrandPrices = payloadForValidation.brandPrices || parsedBrandPrices;

  try {
    const data = {
      name,
      categoryName,
      productTypeName,
      brandName: brandName || null,
      gender: gender || null,
      attributes: parsedAttributes || undefined,
      size: size || null,
      sizeStocks: parsedSizeStocks || undefined,
      brandPrices: finalBrandPrices || undefined,
      price: !isNaN(priceDecimal) ? priceDecimal : 0,
      taxType,
      taxRate: taxRateDecimal,
      taxPercent: taxRateDecimal,
      hsnCode,
      warranty: !isNaN(parseInt(warranty)) ? parseInt(warranty) : 0,
      description,
      barcode: finalBarcode,
      hasBarcode: (hasBarcode === 'true' || hasBarcode === true) || false,
      minDiscount: minDiscount ? parseFloat(minDiscount) : null,
      maxDiscount: maxDiscount ? parseFloat(maxDiscount) : null,
      isTaxInclusive: (isTaxInclusive === 'true' || isTaxInclusive === true) || false,
      imageUrl: imageUrl,
      isActive: req.body.isActive !== undefined ? (req.body.isActive === 'true' || req.body.isActive === true) : true
    };

    if (brandId && !isNaN(parseInt(brandId))) {
      data.brand = { connect: { id: parseInt(brandId) } };
    }

    if (categoryId && !isNaN(parseInt(categoryId))) {
      data.category = { connect: { id: parseInt(categoryId) } };
    }

    if (productTypeId && !isNaN(parseInt(productTypeId))) {
      data.productType = { connect: { id: parseInt(productTypeId) } };
    }

    const product = await prisma.product.create({
      data,
      include: {
        category: {
          include: {
            defaultLabelDesign: true
          }
        },
        productType: true,
        brand: true,
        stocks: true
      }
    });

    // Synchronize initial stock with ProductStock if branch is available
    const branchId = req.body.branchId ? parseInt(req.body.branchId) : (req.user?.branchId || null);
    let targetBranchId = branchId;

    if (!targetBranchId) {
      const firstBranch = await prisma.branch.findFirst({ where: { isActive: true } });
      if (firstBranch) targetBranchId = firstBranch.id;
    }

    if (targetBranchId && totalStockQty >= 0) {
      await prisma.productStock.upsert({
        where: {
          branchId_productId: {
            branchId: targetBranchId,
            productId: product.id
          }
        },
        update: { quantity: totalStockQty },
        create: {
          branchId: targetBranchId,
          productId: product.id,
          quantity: totalStockQty
        }
      });
    }

    res.status(201).json(product);
  } catch (error) {
    if (error.code === 'P2002') {
      res.status(400);
      throw new Error('Barcode already exists');
    }
    throw error;
  }
});

// Update Product
exports.updateProduct = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const {
    name,
    brandId,
    brandName,
    price,
    taxRate,
    taxPercent,
    taxType,
    hsnCode,
    warranty,
    description,
    barcode,
    categoryName,
    categoryId,
    productTypeId,
    productTypeName,
    gender,
    attributes,
    size,
    sizeStocks,
    stock,
    minDiscount,
    maxDiscount,
    isTaxInclusive,
    isActive
  } = req.body;

  const dataToUpdate = {};

  if (name !== undefined) dataToUpdate.name = name;
  if (categoryName !== undefined) dataToUpdate.categoryName = categoryName;
  if (productTypeName !== undefined) dataToUpdate.productTypeName = productTypeName;
  if (gender !== undefined) dataToUpdate.gender = gender || null;
  if (size !== undefined) dataToUpdate.size = size || null;
  if (taxType !== undefined) dataToUpdate.taxType = taxType;
  if (hsnCode !== undefined) dataToUpdate.hsnCode = hsnCode;
  if (description !== undefined) dataToUpdate.description = description;
  if (barcode !== undefined) dataToUpdate.barcode = barcode;

  if (brandId !== undefined) {
    if (brandId && !isNaN(parseInt(brandId))) {
      const assignedBrand = await prisma.brand.findUnique({ where: { id: parseInt(brandId) } });
      dataToUpdate.brand = { connect: { id: parseInt(brandId) } };
      dataToUpdate.brandName = assignedBrand?.name || brandName || null;
    } else {
      dataToUpdate.brand = { disconnect: true };
      dataToUpdate.brandName = null;
    }
  } else if (brandName !== undefined) {
    dataToUpdate.brandName = brandName;
  }

  if (attributes !== undefined) {
    dataToUpdate.attributes = safeJsonParse(attributes);
  }

  if (sizeStocks !== undefined) {
    dataToUpdate.sizeStocks = safeJsonParse(sizeStocks);
  }

  if (req.body.brandPrices !== undefined) {
    dataToUpdate.brandPrices = safeJsonParse(req.body.brandPrices);
  }

  if (price !== undefined && !isNaN(parseFloat(price))) {
    dataToUpdate.price = parseFloat(price);
  }

  if (taxRate !== undefined || taxPercent !== undefined) {
    const taxVal = taxRate !== undefined ? taxRate : taxPercent;
    const parsedTax = parseFloat(taxVal) || 0;
    dataToUpdate.taxRate = parsedTax;
    dataToUpdate.taxPercent = parsedTax;
  }

  if (warranty !== undefined) {
    dataToUpdate.warranty = !isNaN(parseInt(warranty)) ? parseInt(warranty) : 0;
  }

  if (minDiscount !== undefined) dataToUpdate.minDiscount = minDiscount ? parseFloat(minDiscount) : null;
  if (maxDiscount !== undefined) dataToUpdate.maxDiscount = maxDiscount ? parseFloat(maxDiscount) : null;

  if (isTaxInclusive !== undefined) {
    dataToUpdate.isTaxInclusive = (isTaxInclusive === 'true' || isTaxInclusive === true);
  }

  if (isActive !== undefined) {
    dataToUpdate.isActive = (isActive === 'true' || isActive === true);
  }

  if (categoryId !== undefined) {
    if (categoryId && !isNaN(parseInt(categoryId))) {
      dataToUpdate.category = { connect: { id: parseInt(categoryId) } };
    } else {
      dataToUpdate.category = { disconnect: true };
    }
  }

  if (productTypeId !== undefined) {
    if (productTypeId && !isNaN(parseInt(productTypeId))) {
      dataToUpdate.productType = { connect: { id: parseInt(productTypeId) } };
    } else {
      dataToUpdate.productType = { disconnect: true };
    }
  }

  if (req.file) {
    dataToUpdate.imageUrl = '/uploads/' + req.file.filename;
  }

  // Validate Barcode Uniqueness globally & auto-repair auto-generated barcodes
  if (req.body.barcodeIsAutoGenerated !== undefined) {
    dataToUpdate.barcodeIsAutoGenerated = req.body.barcodeIsAutoGenerated;
  }
  await processAndValidateBarcodes(dataToUpdate, id);
  delete dataToUpdate.barcodeIsAutoGenerated;

  let product;
  try {
    product = await prisma.product.update({
      where: { id: parseInt(id) },
      data: dataToUpdate,
      include: {
        category: {
          include: {
            defaultLabelDesign: true
          }
        },
        productType: true,
        brand: true,
        stocks: true
      }
    });
  } catch (error) {
    if (error.code === 'P2002') {
      res.status(400);
      throw new Error('Barcode already exists. Please enter a unique barcode.');
    }
    throw error;
  }

  // If sizeStocks or stock explicitly changed, update ProductStock for branch
  const parsedSizeStocks = safeJsonParse(sizeStocks);
  let updatedStockQty = null;

  if (parsedSizeStocks && Array.isArray(parsedSizeStocks) && parsedSizeStocks.length > 0) {
    updatedStockQty = parsedSizeStocks.reduce((sum, item) => sum + (parseInt(item.stock, 10) || 0), 0);
  } else if (stock !== undefined && stock !== '' && !isNaN(parseInt(stock, 10))) {
    updatedStockQty = parseInt(stock, 10);
  }

  if (updatedStockQty !== null) {
    const branchId = req.body.branchId ? parseInt(req.body.branchId) : (req.user?.branchId || null);
    let targetBranchId = branchId;

    if (!targetBranchId) {
      const firstBranch = await prisma.branch.findFirst({ where: { isActive: true } });
      if (firstBranch) targetBranchId = firstBranch.id;
    }

    if (targetBranchId) {
      await prisma.productStock.upsert({
        where: {
          branchId_productId: {
            branchId: targetBranchId,
            productId: parseInt(id)
          }
        },
        update: { quantity: updatedStockQty },
        create: {
          branchId: targetBranchId,
          productId: parseInt(id),
          quantity: updatedStockQty
        }
      });
    }
  }

  res.json(product);
});

// Delete Product
exports.deleteProduct = asyncHandler(async (req, res) => {
  const { id } = req.params;
  await prisma.product.delete({ where: { id: parseInt(id) } });
  res.json({ message: 'Product deleted' });
});
