-- AlterTable
ALTER TABLE "BarcodeTemplate" ADD COLUMN     "dpi" INTEGER DEFAULT 203,
ADD COLUMN     "labelHeight" DOUBLE PRECISION DEFAULT 20,
ADD COLUMN     "labelWidth" DOUBLE PRECISION DEFAULT 40;
